import { getDb } from "../config/firebase.js";
import { COLLECTIONS, ALERT_THRESHOLDS, SEVERITY_ORDER } from "../config/constants.js";
import admin from "firebase-admin";

/**
 * Alert Engine — Auto-generates emergency alerts based on:
 * 1. Incident severity reaching CRITICAL
 * 2. Multiple sources corroborating
 * 3. Rapid severity escalation
 * 4. Sensor threshold exceedance
 */
export class AlertEngine {
  /**
   * Evaluate whether an incident should trigger an automatic alert.
   *
   * @param {Object} incident - Incident data with severity, confidence, sourceCount
   * @param {Object} context - { isEscalation, previousSeverity, sensorExceedance }
   * @returns {{ shouldAlert, alert, reason }}
   */
  async evaluate(incident, context = {}) {
    const reasons = [];

    // Rule 1: Critical severity
    if (SEVERITY_ORDER[incident.severity] >= SEVERITY_ORDER[ALERT_THRESHOLDS.AUTO_ALERT_SEVERITY]) {
      reasons.push(`Severity reached ${incident.severity.toUpperCase()}`);
    }

    // Rule 2: Sufficient confidence + sources
    if (
      incident.confidence >= ALERT_THRESHOLDS.AUTO_ALERT_CONFIDENCE &&
      incident.sourceCount >= ALERT_THRESHOLDS.MIN_SOURCES_FOR_AUTO_ALERT
    ) {
      reasons.push(
        `Confidence ${(incident.confidence * 100).toFixed(0)}% with ${incident.sourceCount} corroborating sources`
      );
    }

    // Rule 3: Rapid escalation
    if (context.isEscalation && context.previousSeverity) {
      reasons.push(
        `Severity escalated from ${context.previousSeverity} → ${incident.severity}`
      );
    }

    // Rule 4: Sensor threshold breach
    if (context.sensorExceedance && context.sensorExceedance > 0.5) {
      reasons.push(
        `Sensor reading ${(context.sensorExceedance * 100).toFixed(0)}% above threshold`
      );
    }

    const shouldAlert = reasons.length > 0;

    if (!shouldAlert) {
      return { shouldAlert: false, alert: null, reason: "No alert criteria met." };
    }

    // Check for duplicate alerts
    const isDuplicate = await this._checkDuplicate(incident.id);
    if (isDuplicate) {
      return { shouldAlert: false, alert: null, reason: "Alert already exists for this incident." };
    }

    // Generate alert
    const alert = {
      title: `⚠️ ${incident.severity.toUpperCase()} ALERT: ${incident.title || incident.disasterType}`,
      message: this._buildAlertMessage(incident, reasons),
      severity: incident.severity === "critical" ? "Critical" : "High",
      target: this._determineTarget(incident),
      status: "Broadcasting",
      incidentId: incident.id || null,
      disasterType: incident.disasterType,
      location: incident.location || null,
      triggerReasons: reasons,
      autoGenerated: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      createdBy: "ALERT_ENGINE",
    };

    // Write to Firestore
    const db = getDb();
    const docRef = await db.collection(COLLECTIONS.ALERTS).add(alert);

    console.log(`[Alert Engine] Auto-alert created: ${docRef.id} — ${reasons.join("; ")}`);

    return { shouldAlert: true, alert: { id: docRef.id, ...alert }, reason: reasons.join("; ") };
  }

  /**
   * Check if an alert already exists for this incident (within last hour).
   */
  async _checkDuplicate(incidentId) {
    if (!incidentId) return false;
    const db = getDb();
    const cutoff = new Date(Date.now() - 60 * 60 * 1000);
    try {
      const existing = await db
        .collection(COLLECTIONS.ALERTS)
        .where("incidentId", "==", incidentId)
        .where("createdAt", ">=", cutoff)
        .limit(1)
        .get();
      return !existing.empty;
    } catch {
      return false;
    }
  }

  _buildAlertMessage(incident, reasons) {
    const location = incident.location?.address || "Unknown Location";
    return (
      `${incident.disasterType?.toUpperCase() || "INCIDENT"} detected at ${location}. ` +
      `${reasons.join(". ")}. ` +
      `Confidence: ${((incident.confidence || 0) * 100).toFixed(0)}%. ` +
      `Sources: ${incident.sourceCount || 1}.`
    );
  }

  _determineTarget(incident) {
    const targets = [];
    if (incident.severity === "critical") targets.push("All Emergency Services");
    if (["flood", "cyclone", "tsunami"].includes(incident.disasterType)) targets.push("Evacuation Coordinators");
    if (["wildfire", "industrial"].includes(incident.disasterType)) targets.push("Fire & Hazmat Units");
    if (["earthquake", "infrastructure"].includes(incident.disasterType)) targets.push("Search & Rescue Teams");
    return targets.length > 0 ? targets.join(", ") : "All First Responders";
  }
}

export const alertEngine = new AlertEngine();
