import { Router } from "express";
import { getDb } from "../config/firebase.js";
import { COLLECTIONS, OPERATIONAL_ROLES } from "../config/constants.js";
import { authenticateUser, requireRole } from "../middleware/auth.js";
import admin from "firebase-admin";

const router = Router();

/**
 * GET /api/alerts — List alerts with optional filtering
 */
router.get("/", async (req, res) => {
  try {
    const db = getDb();
    const { severity, status, limit: limitStr = "50" } = req.query;
    const limit = Math.min(parseInt(limitStr) || 50, 200);

    let query = db.collection(COLLECTIONS.ALERTS).orderBy("createdAt", "desc").limit(limit);
    if (severity) query = db.collection(COLLECTIONS.ALERTS).where("severity", "==", severity).orderBy("createdAt", "desc").limit(limit);

    const snapshot = await query.get();
    const alerts = snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }));

    res.json({ data: alerts, meta: { count: alerts.length } });
  } catch (error) {
    console.error("[Alerts GET] Error:", error.message);
    res.status(500).json({ error: "FETCH_FAILED", message: error.message });
  }
});

/**
 * POST /api/alerts — Create manual alert (authenticated)
 */
router.post("/", authenticateUser, requireRole(...OPERATIONAL_ROLES), async (req, res) => {
  try {
    const db = getDb();
    const data = req.body;

    const payload = {
      title: data.title || "Emergency Alert",
      message: data.message || "",
      severity: data.severity || "High",
      target: data.target || "All First Responders",
      status: data.status || "Broadcasting",
      autoGenerated: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      createdBy: req.user.uid,
    };

    const docRef = await db.collection(COLLECTIONS.ALERTS).add(payload);

    // Audit log
    await db.collection(COLLECTIONS.AUDIT_LOGS).add({
      action: "BROADCAST_ALERT_DISPATCHED",
      details: `${req.user.email} dispatched: ${payload.title}`,
      user: req.user.email,
      ip: req.ip,
      status: "Success",
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    res.status(201).json({ data: { id: docRef.id, ...payload } });
  } catch (error) {
    console.error("[Alerts POST] Error:", error.message);
    res.status(500).json({ error: "CREATE_FAILED", message: error.message });
  }
});

/**
 * PATCH /api/alerts/:id — Update alert status (authenticated)
 */
router.patch("/:id", authenticateUser, requireRole(...OPERATIONAL_ROLES), async (req, res) => {
  try {
    const db = getDb();
    const docRef = db.collection(COLLECTIONS.ALERTS).doc(req.params.id);
    const doc = await docRef.get();

    if (!doc.exists) {
      return res.status(404).json({ error: "NOT_FOUND", message: "Alert not found." });
    }

    const update = { ...req.body, updatedAt: admin.firestore.FieldValue.serverTimestamp() };
    delete update.createdAt;
    delete update.id;

    await docRef.update(update);
    res.json({ data: { id: req.params.id, ...doc.data(), ...update } });
  } catch (error) {
    console.error("[Alerts PATCH] Error:", error.message);
    res.status(500).json({ error: "UPDATE_FAILED", message: error.message });
  }
});

export default router;
